//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace CadastralViewer.Xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("geoSurveyPacketData", Namespace="", IsNullable=false)]
    public partial class GeoSurveyPacketData {
        
        private Units unitsField;
        
        private JobParameters jobParametersField;
        
        private Accuracy[] accuraciesField;
        
        private Plan[] plansField;
        
        private Point[] pointsField;
        
        private ControlPoint[] controlPointsField;
        
        /// <remarks/>
        public Units units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
        
        /// <remarks/>
        public JobParameters jobParameters {
            get {
                return this.jobParametersField;
            }
            set {
                this.jobParametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("accuracy", IsNullable=false)]
        public Accuracy[] accuracies {
            get {
                return this.accuraciesField;
            }
            set {
                this.accuraciesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("plan", IsNullable=false)]
        public Plan[] plans {
            get {
                return this.plansField;
            }
            set {
                this.plansField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("point", IsNullable=false)]
        public Point[] points {
            get {
                return this.pointsField;
            }
            set {
                this.pointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("controlPoint", IsNullable=false)]
        public ControlPoint[] controlPoints {
            get {
                return this.controlPointsField;
            }
            set {
                this.controlPointsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Units {
        
        private DistanceUnit distanceUnitsField;
        
        private AreaUnit areaUnitsField;
        
        private DirectionUnit angleUnitsField;
        
        private DirectionUnit directionUnitsField;
        
        private DirectionFormat directionFormatField;
        
        /// <remarks/>
        public DistanceUnit distanceUnits {
            get {
                return this.distanceUnitsField;
            }
            set {
                this.distanceUnitsField = value;
            }
        }
        
        /// <remarks/>
        public AreaUnit areaUnits {
            get {
                return this.areaUnitsField;
            }
            set {
                this.areaUnitsField = value;
            }
        }
        
        /// <remarks/>
        public DirectionUnit angleUnits {
            get {
                return this.angleUnitsField;
            }
            set {
                this.angleUnitsField = value;
            }
        }
        
        /// <remarks/>
        public DirectionUnit directionUnits {
            get {
                return this.directionUnitsField;
            }
            set {
                this.directionUnitsField = value;
            }
        }
        
        /// <remarks/>
        public DirectionFormat directionFormat {
            get {
                return this.directionFormatField;
            }
            set {
                this.directionFormatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    public enum DistanceUnit {
        
        /// <remarks/>
        Meter,
        
        /// <remarks/>
        Metre,
        
        /// <remarks/>
        Foot,
        
        /// <remarks/>
        Chain,
        
        /// <remarks/>
        Link,
        
        /// <remarks/>
        Foot_US,
        
        /// <remarks/>
        Chain_US,
        
        /// <remarks/>
        Link_US,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    public enum AreaUnit {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Square meter")]
        Squaremeter,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Square Meter")]
        SquareMeter,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Square foot")]
        Squarefoot,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Square Foot")]
        SquareFoot,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Square link")]
        Squarelink,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Square Link")]
        SquareLink,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    public enum DirectionUnit {
        
        /// <remarks/>
        Radian,
        
        /// <remarks/>
        Degree,
        
        /// <remarks/>
        DMS,
        
        /// <remarks/>
        Gradian,
        
        /// <remarks/>
        Gon,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    public enum DirectionFormat {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("north azimuth")]
        northazimuth,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("south azimuth")]
        southazimuth,
        
        /// <remarks/>
        Polar,
        
        /// <remarks/>
        Quadrant,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ControlPoint {
        
        private int pointIDField;
        
        private string nameField;
        
        private double xField;
        
        private double yField;
        
        private double zField;
        
        private bool zFieldSpecified;
        
        private bool activeField;
        
        private string accuracyXYField;
        
        private string accuracyZField;
        
        private string surveyDateField;
        
        private int typeField;
        
        private int oIDField;
        
        private ExtendedAttribute[] extendedAttributesField;
        
        public ControlPoint() {
            this.activeField = false;
            this.surveyDateField = "none";
            this.typeField = 0;
        }
        
        /// <remarks/>
        public int pointID {
            get {
                return this.pointIDField;
            }
            set {
                this.pointIDField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        public double z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zSpecified {
            get {
                return this.zFieldSpecified;
            }
            set {
                this.zFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public string accuracyXY {
            get {
                return this.accuracyXYField;
            }
            set {
                this.accuracyXYField = value;
            }
        }
        
        /// <remarks/>
        public string accuracyZ {
            get {
                return this.accuracyZField;
            }
            set {
                this.accuracyZField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("none")]
        public string surveyDate {
            get {
                return this.surveyDateField;
            }
            set {
                this.surveyDateField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public int oID {
            get {
                return this.oIDField;
            }
            set {
                this.oIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("extendedAttribute", IsNullable=false)]
        public ExtendedAttribute[] extendedAttributes {
            get {
                return this.extendedAttributesField;
            }
            set {
                this.extendedAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtendedAttribute {
        
        private string nameField;
        
        private string valueField;
        
        private ExtendedAttributeType typeField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public ExtendedAttributeType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    public enum ExtendedAttributeType {
        
        /// <remarks/>
        VT_I2,
        
        /// <remarks/>
        VT_I4,
        
        /// <remarks/>
        VT_R4,
        
        /// <remarks/>
        VT_R8,
        
        /// <remarks/>
        VT_DATE,
        
        /// <remarks/>
        VT_BSTR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Point {
        
        private int pointNoField;
        
        private double xField;
        
        private double yField;
        
        private double zField;
        
        private bool zFieldSpecified;
        
        private int typeField;
        
        private bool typeFieldSpecified;
        
        private CadastralPointCategory categoryField;
        
        private bool historicalField;
        
        private string nameField;
        
        private string legalStartDateField;
        
        private string legalEndDateField;
        
        private bool centerPointField;
        
        private int oIDField;
        
        private ExtendedAttribute[] extendedAttributesField;
        
        private double maxDEField;
        
        private bool maxDEFieldSpecified;
        
        private double maxDNField;
        
        private bool maxDNFieldSpecified;
        
        public Point() {
            this.categoryField = CadastralPointCategory.Boundary;
            this.historicalField = false;
            this.legalStartDateField = "none";
            this.legalEndDateField = "none";
            this.centerPointField = false;
            this.oIDField = 0;
        }
        
        /// <remarks/>
        public int pointNo {
            get {
                return this.pointNoField;
            }
            set {
                this.pointNoField = value;
            }
        }
        
        /// <remarks/>
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        public double z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zSpecified {
            get {
                return this.zFieldSpecified;
            }
            set {
                this.zFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(CadastralPointCategory.Boundary)]
        public CadastralPointCategory category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool historical {
            get {
                return this.historicalField;
            }
            set {
                this.historicalField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("none")]
        public string legalStartDate {
            get {
                return this.legalStartDateField;
            }
            set {
                this.legalStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("none")]
        public string legalEndDate {
            get {
                return this.legalEndDateField;
            }
            set {
                this.legalEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool centerPoint {
            get {
                return this.centerPointField;
            }
            set {
                this.centerPointField = value;
            }
        }
        
        /// <remarks/>
        public int oID {
            get {
                return this.oIDField;
            }
            set {
                this.oIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("extendedAttribute", IsNullable=false)]
        public ExtendedAttribute[] ExtendedAttributes {
            get {
                return this.extendedAttributesField;
            }
            set {
                this.extendedAttributesField = value;
            }
        }
        
        /// <remarks/>
        public double maxDE {
            get {
                return this.maxDEField;
            }
            set {
                this.maxDEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxDESpecified {
            get {
                return this.maxDEFieldSpecified;
            }
            set {
                this.maxDEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double maxDN {
            get {
                return this.maxDNField;
            }
            set {
                this.maxDNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxDNSpecified {
            get {
                return this.maxDNFieldSpecified;
            }
            set {
                this.maxDNFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    public enum CadastralPointCategory {
        
        /// <remarks/>
        Boundary,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Tie-in")]
        Tiein,
        
        /// <remarks/>
        Construction,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinePoint {
        
        private int fromPointField;
        
        private int toPointField;
        
        private int linePointField;
        
        private int oIDField;
        
        public LinePoint() {
            this.oIDField = 0;
        }
        
        /// <remarks/>
        public int fromPoint {
            get {
                return this.fromPointField;
            }
            set {
                this.fromPointField = value;
            }
        }
        
        /// <remarks/>
        public int toPoint {
            get {
                return this.toPointField;
            }
            set {
                this.toPointField = value;
            }
        }
        
        /// <remarks/>
        public int linePoint {
            get {
                return this.linePointField;
            }
            set {
                this.linePointField = value;
            }
        }
        
        /// <remarks/>
        public int oID {
            get {
                return this.oIDField;
            }
            set {
                this.oIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Line {
        
        private int fromPointField;
        
        private int toPointField;
        
        private double bearingField;
        
        private double distanceField;
        
        private int typeField;
        
        private bool calculatedField;
        
        private CadastralLineCategory categoryField;
        
        private double radiusField;
        
        private bool radiusFieldSpecified;
        
        private double arcLengthField;
        
        private bool arcLengthFieldSpecified;
        
        private double deltaField;
        
        private bool deltaFieldSpecified;
        
        private int centerPointField;
        
        private bool centerPointFieldSpecified;
        
        private double radialBearingField;
        
        private bool radialBearingFieldSpecified;
        
        private double tangentBearingField;
        
        private bool tangentBearingFieldSpecified;
        
        private double internalAngleField;
        
        private bool internalAngleFieldSpecified;
        
        private int referenceObjectField;
        
        private bool referenceObjectFieldSpecified;
        
        private CadastralLineParameter lineParameterField;
        
        private double computedMinusObservedField;
        
        private bool computedMinusObservedFieldSpecified;
        
        private int accuracyField;
        
        private int oIDField;
        
        private ExtendedAttribute[] extendedAttributesField;
        
        public Line() {
            this.typeField = 0;
            this.calculatedField = false;
            this.categoryField = CadastralLineCategory.Boundary;
            this.lineParameterField = CadastralLineParameter.bearingAndDistance;
            this.accuracyField = 0;
            this.oIDField = 0;
        }
        
        /// <remarks/>
        public int fromPoint {
            get {
                return this.fromPointField;
            }
            set {
                this.fromPointField = value;
            }
        }
        
        /// <remarks/>
        public int toPoint {
            get {
                return this.toPointField;
            }
            set {
                this.toPointField = value;
            }
        }
        
        /// <remarks/>
        public double bearing {
            get {
                return this.bearingField;
            }
            set {
                this.bearingField = value;
            }
        }
        
        /// <remarks/>
        public double distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool calculated {
            get {
                return this.calculatedField;
            }
            set {
                this.calculatedField = value;
            }
        }
        
        /// <remarks/>
        public CadastralLineCategory category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public double radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool radiusSpecified {
            get {
                return this.radiusFieldSpecified;
            }
            set {
                this.radiusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double arcLength {
            get {
                return this.arcLengthField;
            }
            set {
                this.arcLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arcLengthSpecified {
            get {
                return this.arcLengthFieldSpecified;
            }
            set {
                this.arcLengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double delta {
            get {
                return this.deltaField;
            }
            set {
                this.deltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deltaSpecified {
            get {
                return this.deltaFieldSpecified;
            }
            set {
                this.deltaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int centerPoint {
            get {
                return this.centerPointField;
            }
            set {
                this.centerPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool centerPointSpecified {
            get {
                return this.centerPointFieldSpecified;
            }
            set {
                this.centerPointFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double radialBearing {
            get {
                return this.radialBearingField;
            }
            set {
                this.radialBearingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool radialBearingSpecified {
            get {
                return this.radialBearingFieldSpecified;
            }
            set {
                this.radialBearingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double tangentBearing {
            get {
                return this.tangentBearingField;
            }
            set {
                this.tangentBearingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tangentBearingSpecified {
            get {
                return this.tangentBearingFieldSpecified;
            }
            set {
                this.tangentBearingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double internalAngle {
            get {
                return this.internalAngleField;
            }
            set {
                this.internalAngleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool internalAngleSpecified {
            get {
                return this.internalAngleFieldSpecified;
            }
            set {
                this.internalAngleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int referenceObject {
            get {
                return this.referenceObjectField;
            }
            set {
                this.referenceObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool referenceObjectSpecified {
            get {
                return this.referenceObjectFieldSpecified;
            }
            set {
                this.referenceObjectFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(CadastralLineParameter.bearingAndDistance)]
        public CadastralLineParameter lineParameter {
            get {
                return this.lineParameterField;
            }
            set {
                this.lineParameterField = value;
            }
        }
        
        /// <remarks/>
        public double computedMinusObserved {
            get {
                return this.computedMinusObservedField;
            }
            set {
                this.computedMinusObservedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool computedMinusObservedSpecified {
            get {
                return this.computedMinusObservedFieldSpecified;
            }
            set {
                this.computedMinusObservedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int accuracy {
            get {
                return this.accuracyField;
            }
            set {
                this.accuracyField = value;
            }
        }
        
        /// <remarks/>
        public int oID {
            get {
                return this.oIDField;
            }
            set {
                this.oIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("extendedAttribute", IsNullable=false)]
        public ExtendedAttribute[] ExtendedAttributes {
            get {
                return this.extendedAttributesField;
            }
            set {
                this.extendedAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    public enum CadastralLineCategory {
        
        /// <remarks/>
        Boundary,
        
        /// <remarks/>
        Dependent,
        
        /// <remarks/>
        Precise,
        
        /// <remarks/>
        Connection,
        
        /// <remarks/>
        Radial,
        
        /// <remarks/>
        Road,
        
        /// <remarks/>
        OriginConnection,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    public enum CadastralLineParameter {
        
        /// <remarks/>
        bearingAndDistance,
        
        /// <remarks/>
        angleAndDistance,
        
        /// <remarks/>
        chordBearingAndDeltaAndRadius,
        
        /// <remarks/>
        deltaAndRadius,
        
        /// <remarks/>
        chordBearingAndChordLengthAndRadius,
        
        /// <remarks/>
        ChordBearingAndChordLengthAndRadius,
        
        /// <remarks/>
        chordLengthAndRadius,
        
        /// <remarks/>
        chordBearingAndArcLengthAndRadius,
        
        /// <remarks/>
        arcLengthAndRadius,
        
        /// <remarks/>
        chordBearingAndDeltaAndArcLength,
        
        /// <remarks/>
        deltaAndArcLength,
        
        /// <remarks/>
        radialBearingAndDeltaAndRadius,
        
        /// <remarks/>
        radialBearingAndChordLengthAndRadius,
        
        /// <remarks/>
        radialBearingAndArcLengthAndRadius,
        
        /// <remarks/>
        radialBearingAndDeltaAndArcLength,
        
        /// <remarks/>
        tangentBearingAndDeltaAndRadius,
        
        /// <remarks/>
        tangentBearingAndChordLengthAndRadius,
        
        /// <remarks/>
        tangentBearingAndArcLengthAndRadius,
        
        /// <remarks/>
        tangentBearingAndDeltaAndArcLength,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Parcel {
        
        private string nameField;
        
        private int typeField;
        
        private string statedAreaField;
        
        private bool compiledField;
        
        private bool historicalField;
        
        private System.DateTime legalStartDateField;
        
        private bool legalStartDateFieldSpecified;
        
        private System.DateTime legalEndDateField;
        
        private bool legalEndDateFieldSpecified;
        
        private int groupIDField;
        
        private int accuracyField;
        
        private double rotationField;
        
        private double scaleField;
        
        private double backsightBearingField;
        
        private bool backsightBearingFieldSpecified;
        
        private bool unclosedField;
        
        private double miscloseRatioField;
        
        private bool miscloseRatioFieldSpecified;
        
        private double miscloseBearingField;
        
        private bool miscloseBearingFieldSpecified;
        
        private double miscloseDistanceField;
        
        private bool joinedField;
        
        private bool trueMidBearingField;
        
        private double shapeStdErrorEField;
        
        private bool shapeStdErrorEFieldSpecified;
        
        private double shapeStdErrorNField;
        
        private bool shapeStdErrorNFieldSpecified;
        
        private int oIDField;
        
        private bool lockedField;
        
        private bool constructionField;
        
        private ExtendedAttribute[] extendedAttributesField;
        
        private Line[] linesField;
        
        private LinePoint[] linePointsField;
        
        public Parcel() {
            this.typeField = 0;
            this.compiledField = false;
            this.historicalField = false;
            this.groupIDField = 0;
            this.accuracyField = 0;
            this.rotationField = 0;
            this.scaleField = 1;
            this.unclosedField = false;
            this.miscloseDistanceField = 0;
            this.joinedField = false;
            this.trueMidBearingField = false;
            this.oIDField = 0;
            this.lockedField = true;
            this.constructionField = false;
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string statedArea {
            get {
                return this.statedAreaField;
            }
            set {
                this.statedAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool compiled {
            get {
                return this.compiledField;
            }
            set {
                this.compiledField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool historical {
            get {
                return this.historicalField;
            }
            set {
                this.historicalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime legalStartDate {
            get {
                return this.legalStartDateField;
            }
            set {
                this.legalStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool legalStartDateSpecified {
            get {
                return this.legalStartDateFieldSpecified;
            }
            set {
                this.legalStartDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime legalEndDate {
            get {
                return this.legalEndDateField;
            }
            set {
                this.legalEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool legalEndDateSpecified {
            get {
                return this.legalEndDateFieldSpecified;
            }
            set {
                this.legalEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int groupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int accuracy {
            get {
                return this.accuracyField;
            }
            set {
                this.accuracyField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public double rotation {
            get {
                return this.rotationField;
            }
            set {
                this.rotationField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(1)]
        public double scale {
            get {
                return this.scaleField;
            }
            set {
                this.scaleField = value;
            }
        }
        
        /// <remarks/>
        public double backsightBearing {
            get {
                return this.backsightBearingField;
            }
            set {
                this.backsightBearingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool backsightBearingSpecified {
            get {
                return this.backsightBearingFieldSpecified;
            }
            set {
                this.backsightBearingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool unclosed {
            get {
                return this.unclosedField;
            }
            set {
                this.unclosedField = value;
            }
        }
        
        /// <remarks/>
        public double miscloseRatio {
            get {
                return this.miscloseRatioField;
            }
            set {
                this.miscloseRatioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool miscloseRatioSpecified {
            get {
                return this.miscloseRatioFieldSpecified;
            }
            set {
                this.miscloseRatioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double miscloseBearing {
            get {
                return this.miscloseBearingField;
            }
            set {
                this.miscloseBearingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool miscloseBearingSpecified {
            get {
                return this.miscloseBearingFieldSpecified;
            }
            set {
                this.miscloseBearingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public double miscloseDistance {
            get {
                return this.miscloseDistanceField;
            }
            set {
                this.miscloseDistanceField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool joined {
            get {
                return this.joinedField;
            }
            set {
                this.joinedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool trueMidBearing {
            get {
                return this.trueMidBearingField;
            }
            set {
                this.trueMidBearingField = value;
            }
        }
        
        /// <remarks/>
        public double shapeStdErrorE {
            get {
                return this.shapeStdErrorEField;
            }
            set {
                this.shapeStdErrorEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shapeStdErrorESpecified {
            get {
                return this.shapeStdErrorEFieldSpecified;
            }
            set {
                this.shapeStdErrorEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double shapeStdErrorN {
            get {
                return this.shapeStdErrorNField;
            }
            set {
                this.shapeStdErrorNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shapeStdErrorNSpecified {
            get {
                return this.shapeStdErrorNFieldSpecified;
            }
            set {
                this.shapeStdErrorNFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int oID {
            get {
                return this.oIDField;
            }
            set {
                this.oIDField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool locked {
            get {
                return this.lockedField;
            }
            set {
                this.lockedField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool construction {
            get {
                return this.constructionField;
            }
            set {
                this.constructionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("extendedAttribute", IsNullable=false)]
        public ExtendedAttribute[] extendedAttributes {
            get {
                return this.extendedAttributesField;
            }
            set {
                this.extendedAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("line", IsNullable=false)]
        public Line[] lines {
            get {
                return this.linesField;
            }
            set {
                this.linesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("linePoint", IsNullable=false)]
        public LinePoint[] linePoints {
            get {
                return this.linePointsField;
            }
            set {
                this.linePointsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Plan {
        
        private string nameField;
        
        private string descriptionField;
        
        private string surveyorField;
        
        private string companyField;
        
        private string surveyDateField;
        
        private System.DateTime legalDateField;
        
        private bool legalDateFieldSpecified;
        
        private DirectionUnit angleUnitsField;
        
        private AreaUnit areaUnitsField;
        
        private DistanceUnit distanceUnitsField;
        
        private DirectionFormat directionFormatField;
        
        private CadastralLineParameter lineParametersField;
        
        private bool distanceAtGroundField;
        
        private double combinedGridFactorField;
        
        private bool trueMidBearingField;
        
        private int accuracyField;
        
        private int oIDField;
        
        private bool internalAnglesField;
        
        private ExtendedAttribute[] extendedAttributesField;
        
        private Parcel[] parcelsField;
        
        public Plan() {
            this.angleUnitsField = DirectionUnit.Degree;
            this.areaUnitsField = AreaUnit.Squaremeter;
            this.distanceUnitsField = DistanceUnit.Meter;
            this.directionFormatField = DirectionFormat.northazimuth;
            this.lineParametersField = CadastralLineParameter.bearingAndDistance;
            this.distanceAtGroundField = true;
            this.combinedGridFactorField = 1;
            this.trueMidBearingField = false;
            this.accuracyField = 0;
            this.oIDField = 0;
            this.internalAnglesField = false;
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string surveyor {
            get {
                return this.surveyorField;
            }
            set {
                this.surveyorField = value;
            }
        }
        
        /// <remarks/>
        public string company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string surveyDate {
            get {
                return this.surveyDateField;
            }
            set {
                this.surveyDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime legalDate {
            get {
                return this.legalDateField;
            }
            set {
                this.legalDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool legalDateSpecified {
            get {
                return this.legalDateFieldSpecified;
            }
            set {
                this.legalDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(DirectionUnit.Degree)]
        public DirectionUnit angleUnits {
            get {
                return this.angleUnitsField;
            }
            set {
                this.angleUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(AreaUnit.Squaremeter)]
        public AreaUnit areaUnits {
            get {
                return this.areaUnitsField;
            }
            set {
                this.areaUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(DistanceUnit.Meter)]
        public DistanceUnit distanceUnits {
            get {
                return this.distanceUnitsField;
            }
            set {
                this.distanceUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(DirectionFormat.northazimuth)]
        public DirectionFormat directionFormat {
            get {
                return this.directionFormatField;
            }
            set {
                this.directionFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(CadastralLineParameter.bearingAndDistance)]
        public CadastralLineParameter lineParameters {
            get {
                return this.lineParametersField;
            }
            set {
                this.lineParametersField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool distanceAtGround {
            get {
                return this.distanceAtGroundField;
            }
            set {
                this.distanceAtGroundField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(1)]
        public double combinedGridFactor {
            get {
                return this.combinedGridFactorField;
            }
            set {
                this.combinedGridFactorField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool trueMidBearing {
            get {
                return this.trueMidBearingField;
            }
            set {
                this.trueMidBearingField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int accuracy {
            get {
                return this.accuracyField;
            }
            set {
                this.accuracyField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int oID {
            get {
                return this.oIDField;
            }
            set {
                this.oIDField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool internalAngles {
            get {
                return this.internalAnglesField;
            }
            set {
                this.internalAnglesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("extendedAttribute", IsNullable=false)]
        public ExtendedAttribute[] extendedAttributes {
            get {
                return this.extendedAttributesField;
            }
            set {
                this.extendedAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("parcel", IsNullable=false)]
        public Parcel[] parcels {
            get {
                return this.parcelsField;
            }
            set {
                this.parcelsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Accuracy {
        
        private int categoryField;
        
        private string descriptionField;
        
        private double brgSDField;
        
        private double distSDField;
        
        private double pPMField;
        
        private bool defaultField;
        
        private bool compiledField;
        
        private bool compiledFieldSpecified;
        
        public Accuracy() {
            this.defaultField = true;
        }
        
        /// <remarks/>
        public int category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double brgSD {
            get {
                return this.brgSDField;
            }
            set {
                this.brgSDField = value;
            }
        }
        
        /// <remarks/>
        public double distSD {
            get {
                return this.distSDField;
            }
            set {
                this.distSDField = value;
            }
        }
        
        /// <remarks/>
        public double pPM {
            get {
                return this.pPMField;
            }
            set {
                this.pPMField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        public bool compiled {
            get {
                return this.compiledField;
            }
            set {
                this.compiledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool compiledSpecified {
            get {
                return this.compiledFieldSpecified;
            }
            set {
                this.compiledFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JobParameters {
        
        private string ownerField;
        
        private string packetIdField;
        
        private string esriSpatialReferenceField;
        
        private string versionField;
        
        private double angleToleranceField;
        
        private bool angleToleranceFieldSpecified;
        
        private double distanceToleranceField;
        
        private bool distanceToleranceFieldSpecified;
        
        private double linePointToleranceField;
        
        private bool linePointToleranceFieldSpecified;
        
        private double straightLineToleranceField;
        
        private bool straightLineToleranceFieldSpecified;
        
        private double forceLinePointToleranceField;
        
        private bool forceLinePointToleranceFieldSpecified;
        
        private double closePointToleranceField;
        
        private bool closePointToleranceFieldSpecified;
        
        /// <remarks/>
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        public string packetId {
            get {
                return this.packetIdField;
            }
            set {
                this.packetIdField = value;
            }
        }
        
        /// <remarks/>
        public string esriSpatialReference {
            get {
                return this.esriSpatialReferenceField;
            }
            set {
                this.esriSpatialReferenceField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public double angleTolerance {
            get {
                return this.angleToleranceField;
            }
            set {
                this.angleToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool angleToleranceSpecified {
            get {
                return this.angleToleranceFieldSpecified;
            }
            set {
                this.angleToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double distanceTolerance {
            get {
                return this.distanceToleranceField;
            }
            set {
                this.distanceToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distanceToleranceSpecified {
            get {
                return this.distanceToleranceFieldSpecified;
            }
            set {
                this.distanceToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double linePointTolerance {
            get {
                return this.linePointToleranceField;
            }
            set {
                this.linePointToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool linePointToleranceSpecified {
            get {
                return this.linePointToleranceFieldSpecified;
            }
            set {
                this.linePointToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double straightLineTolerance {
            get {
                return this.straightLineToleranceField;
            }
            set {
                this.straightLineToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool straightLineToleranceSpecified {
            get {
                return this.straightLineToleranceFieldSpecified;
            }
            set {
                this.straightLineToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double forceLinePointTolerance {
            get {
                return this.forceLinePointToleranceField;
            }
            set {
                this.forceLinePointToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool forceLinePointToleranceSpecified {
            get {
                return this.forceLinePointToleranceFieldSpecified;
            }
            set {
                this.forceLinePointToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double closePointTolerance {
            get {
                return this.closePointToleranceField;
            }
            set {
                this.closePointToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool closePointToleranceSpecified {
            get {
                return this.closePointToleranceFieldSpecified;
            }
            set {
                this.closePointToleranceFieldSpecified = value;
            }
        }
    }
}
