// <remarks>
// Copyright 2008 - Steve Stanton. This file is part of Backsight
//
// Backsight is free software; you can redistribute it and/or modify it under the terms
// of the GNU Lesser General Public License as published by the Free Software Foundation;
// either version 3 of the License, or (at your option) any later version.
//
// Backsight is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
// </remarks>

using System;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;

using Backsight.Data;
using Backsight.Environment;

namespace Backsight.Editor.Database
{
    /// <summary>
    /// Miscellaneous helper methods that relate to the database.
    /// </summary>
    static class DbUtil
    {
        /// <summary>
        /// Obtains the last identity value assigned using the supplied connection.
        /// </summary>
        /// <param name="c">The connection involved</param>
        /// <returns>The last ID that was assigned</returns>
        public static uint GetLastId(SqlConnection c)
        {
            SqlCommand cmd = new SqlCommand("SELECT SCOPE_IDENTITY()", c);
            object o = cmd.ExecuteScalar();
            return Convert.ToUInt32(o);
        }

        /// <summary>
        /// Expresses a DateTime value according to ISO8601,
        /// (matching CONVERT style 126)
        /// </summary>
        /// <param name="dt">The date and time to respresent</param>
        /// <returns>The standardized string used to refer to the date</returns>
        public static string GetDateTimeString(DateTime dt)
        {
            return String.Format("CONVERT(DATETIME, '{0}', 126)", dt.ToString("s"));
        }

        /// <summary>
        /// Executes a SELECT statement using the specified connection 
        /// </summary>
        /// <param name="c">The database connection to use</param>
        /// <param name="sql">The select statement</param>
        /// <returns>The retrieved data</returns>
        public static DataTable ExecuteSelect(SqlConnection c, string sql)
        {
            //Trace.WriteLine(sql);
            SqlCommand cmd = new SqlCommand(sql, c);
            SqlDataAdapter adapter = new SqlDataAdapter(cmd);
            DataTable dt = new DataTable();
            adapter.MissingSchemaAction = MissingSchemaAction.AddWithKey;
            adapter.Fill(dt);
            return dt;
        }

        /// <summary>
        /// Executes an INSERT, UPDATE, or DELETE statement using the current database connection.
        /// </summary>
        /// <param name="sql">The SQL to execute</param>
        /// <returns>The number of rows affected by the statement</returns>
        public static int ExecuteNonQuery(string sql)
        {
            using (IConnection ic = ConnectionFactory.Create())
            {
                Trace.WriteLine(sql);
                SqlCommand cmd = new SqlCommand(sql, ic.Value);
                return cmd.ExecuteNonQuery();
            }
        }

        /// <summary>
        /// Executes a simple INSERT statement (one that inserts just one row) into a table
        /// where the primary key is an identity value generated by the database. If you
        /// want to execute an insert involving many rows, you must use <see cref="ExecuteNonQuery"/>
        /// </summary>
        /// <param name="sql">The insert statement</param>
        /// <returns>The assigned row ID</returns>
        public static uint ExecuteIdentityInsert(string sql)
        {
            using (IConnection ic = ConnectionFactory.Create())
            {
                Trace.WriteLine(sql);
                SqlConnection c = ic.Value;
                SqlCommand cmd = new SqlCommand(sql, c);
                if (cmd.ExecuteNonQuery()==1)
                    return DbUtil.GetLastId(c);

                throw new Exception("Insert failed to add a single row: "+sql);
            }
        }

        /// <summary>
        /// Creates a new row for a database table
        /// </summary>
        /// <param name="t">The table of interest</param>
        /// <returns>A new row in the table (not yet inserted, with default data for
        /// all columns)</returns>
        internal static DataRow CreateNewRow(ITable t)
        {
            using (IConnection ic = ConnectionFactory.Create())
            {
                string sql = String.Format("SELECT * FROM {0} WHERE 1=0", t.TableName);
                SqlDataAdapter adapter = new SqlDataAdapter(sql, ic.Value);
                DataTable dt = new DataTable(t.TableName);

                // Ensure the length is defined for char columns
                adapter.MissingSchemaAction = MissingSchemaAction.AddWithKey;

                adapter.Fill(dt);
                return dt.NewRow();
            }
        }

        /// <summary>
        /// Saves a row in the database (adds if the <see cref="DataRow.RowState"/> has
        /// a value of <c>DataRowState.Detached</c>, otherwise attempts to update). This
        /// logic may well be defective in a situation where the row has already been added
        /// to a <c>DataTable</c>.
        /// </summary>
        /// <param name="row">The row to add. Usually a row that was created via a
        /// prior call to <see cref="CreateNewRow"/> (the important thing is that
        /// the table name must be defined as part of the rows associated <c>DataTable</c>)</param>
        /// <remarks>This makes use of the <see cref="SqlCommandBuilder"/> class to
        /// generate the relevant insert statement, which requires that the table involved
        /// must have a primary key (if not, you will get an exception)
        /// </remarks>
        /// <exception cref="ArgumentException">If the <see cref="DataTable"/> associated
        /// with the supplied row does not contain a defined table name.</exception>
        public static void SaveRow(DataRow row)
        {
            DataTable dt = row.Table;
            string tableName = dt.TableName;
            if (String.IsNullOrEmpty(tableName))
                throw new ArgumentException("Table name for row is not defined");

            using (IConnection ic = ConnectionFactory.Create())
            {
                SqlDataAdapter a = new SqlDataAdapter("SELECT * FROM " + tableName, ic.Value);
                SqlCommandBuilder cb = new SqlCommandBuilder(a);
                if (row.RowState == DataRowState.Detached)
                    dt.Rows.Add(row);

                int nRows = a.Update(dt);
                Debug.Assert(nRows == 1);
            }
        }
    }
}
