<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.4"/>
        <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1"/>
        <PackageReference Include="Mapsui" Version="5.1.0" />
        <PackageReference Include="Mapsui.Avalonia12" Version="5.1.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
        <PackageReference Include="RepoDb" Version="1.14.0" />
        <PackageReference Include="RepoDb.Sqlite.Microsoft" Version="1.14.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Backsight.Database\Backsight.Database.csproj" />
      <ProjectReference Include="..\Backsight.Model\Backsight.Model.csproj" />
    </ItemGroup>

    <ItemGroup>
      <AvaloniaResource Include="Assets\ClosedHand.png" />
      <AvaloniaResource Include="Assets\OpenHand.png" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Windows\NewMapViewModel.cs">
        <DependentUpon>NewMapWindow.axaml</DependentUpon>
      </Compile>
      <Compile Update="Windows\SplashWindow.axaml.cs">
        <DependentUpon>SplashWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Windows\SplashViewModel.cs">
        <DependentUpon>SplashWindow.axaml</DependentUpon>
      </Compile>
      <Compile Update="Windows\StartupWindow.axaml.cs">
        <DependentUpon>StartupWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Windows\StartupViewModel.cs">
        <DependentUpon>StartupWindow.axaml</DependentUpon>
      </Compile>
      <Compile Update="Windows\OpenMapWindow.axaml.cs">
        <DependentUpon>OpenMapWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Windows\OpenMapViewModel.cs">
        <DependentUpon>OpenMapWindow.axaml</DependentUpon>
      </Compile>
      <Compile Update="Windows\MapEditorWindow.axaml.cs">
        <DependentUpon>MapEditorWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Windows\MapEditorViewModel.cs">
        <DependentUpon>MapEditorWindow.axaml</DependentUpon>
      </Compile>
      <Compile Update="Windows\MessageBoxViewModel.cs">
        <DependentUpon>MessageBoxWindow.axaml</DependentUpon>
      </Compile>
      <Compile Update="Windows\PropertyDisplayViewModel.cs">
        <DependentUpon>PropertyDisplay.axaml</DependentUpon>
      </Compile>
      <Compile Update="Windows\SimplePropertyGridViewModel.cs">
        <DependentUpon>SimplePropertyGrid.axaml</DependentUpon>
      </Compile>
      <Compile Update="Windows\SaveChangesViewModel.cs">
        <DependentUpon>SaveChangesWindow.axaml</DependentUpon>
      </Compile>
    </ItemGroup>
</Project>
