namespace Backsight.Model;

/// <written by="Steve Stanton" on="17-NOV-2011"/>
/// <summary>
/// Numeric values that are used to identify the various data fields involved in
/// the definition of edits.
/// </summary>
/// <remarks>
/// These values are used to help avoid potential typos that might not get caught until
/// run-time. As things currently stand, these values do not get persisted, so you can
/// re-arrange them as you please. This may need to change if a binary writer is provided.</remarks>
public enum DataField : ushort
{
    Empty = 0,
    X,
    Y,
    Z,
    Id,
    Ids,
    Point,
    Points,
    NewPoint,
    Line,
    Line1,
    Line2,
    Lines,
    NewLine,
    NewLine1,
    NewLine2,
    Text,
    Length,
    Features,
    Result,
    Test,
    Offset,
    Face,
    OtherSide,
    Type,
    Radius,
    Direction,
    Direction1,
    Direction2,
    Edit,
    Distance,
    Distance1,
    Distance2,
    From,
    To,
    DirLine,
    DistLine,
    ForeignKey,
    Key,
    Arc,
    ClosingPoint,
    Topological,
    Left,
    PolygonX,
    PolygonY,
    PositionRatio,
    Center,
    CloseTo,
    SplitAfter,
    SplitAfter1,
    SplitAfter2,
    SplitBefore,
    SplitBefore1,
    SplitBefore2,
    Default,
    From1,
    From2,
    RefLine,
    ReverseArc,
    Term1,
    Term2,
    DeactivatedLabel,
    End,
    Entity,
    EntryString,
    FirstArc,
    Flipped,
    Label,
    NewX,
    NewY,
    OldX,
    OldY,
    RevisedEdit,
    RevisedEdits,
    Value,
    Start,
    Table,
    Template,
    Width,
    Backsight,
    Base,
    Clockwise,
    Data,
    DefaultEntryUnit,
    Delete,
    Font,
    Height,
    OldPolygonX,
    OldPolygonY,
    Rotation,
    EntryFromEnd,
    ExtendFromEnd,
    Fixed,
    Unit,
    UpdatedPoint,
    Sections,
    ProjectId,
    ProjectName,
    UserName,
    MachineName,
    CoordinateSystem,
    When,
    LayerId,
    StartTime,
    EndTime,
    GroupId,
    LowestId,
    HighestId,
    Source,
    PointType,
    LineType,
    LineString,
    PrimaryFaceId,
    AlternateFaces,
}