// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.0.0.19191
//    <NameSpace>Backsight.Editor.Xml</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLasyLoading>False</EnableLasyLoading><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><DisableDebug>False</DisableDebug><CustomUsings></CustomUsings>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Backsight.Editor.Xml {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    public partial class EditData {
        
        private List<OperationData> operationField;
        
        public EditData() {
            this.operationField = new List<OperationData>();
        }
        
        public List<OperationData> Operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineExtensionUpdateData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TrimLineData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextRotationData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SimpleLineSubdivisionData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetTopologyData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RadialData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyChangeData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonSubdivisionData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PathData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParallelLineData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewSegmentData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewRowTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewPointData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewMiscTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewKeyTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewCircleData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewArcData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MoveTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MovePolygonPositionData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineSubdivisionData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineExtensionData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntersectTwoLinesData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntersectTwoDistancesData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntersectTwoDirectionsData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntersectDirectionAndLineData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntersectDirectionAndDistanceData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImportData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetControlData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeletionData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttachPointData))]
    public abstract partial class OperationData {
        
        private string idField;
        
        private string previousIdField;
        
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        public string PreviousId {
            get {
                return this.previousIdField;
            }
            set {
                this.previousIdField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StraightLegData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CircularLegData))]
    public abstract partial class LegData {
        
        private List<SpanData> spanField;
        
        private byte faceField;
        
        public LegData() {
            this.spanField = new List<SpanData>();
            this.faceField = ((byte)(0));
        }
        
        public List<SpanData> Span {
            get {
                return this.spanField;
            }
            set {
                this.spanField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(typeof(byte), "0")]
        public byte Face {
            get {
                return this.faceField;
            }
            set {
                this.faceField = value;
            }
        }
    }
    
    public partial class SpanData {
        
        private DistanceData lengthField;
        
        private object itemField;
        
        private CalculatedFeatureData endPointField;
        
        public SpanData() {
            this.endPointField = new CalculatedFeatureData();
            this.lengthField = new DistanceData();
        }
        
        public DistanceData Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        public CalculatedFeatureData EndPoint {
            get {
                return this.endPointField;
            }
            set {
                this.endPointField = value;
            }
        }
    }
    
    public partial class DistanceData : ObservationData {
        
        private double valueField;
        
        private int unitField;
        
        private bool fixedField;
        
        public DistanceData() {
            this.unitField = 0;
            this.fixedField = false;
        }
        
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Fixed {
            get {
                return this.fixedField;
            }
            set {
                this.fixedField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DistanceData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OffsetData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OffsetPointData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OffsetDistanceData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DirectionData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParallelData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BearingData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AngleData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeflectionData))]
    public abstract partial class ObservationData {
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OffsetPointData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OffsetDistanceData))]
    public abstract partial class OffsetData : ObservationData {
    }
    
    public partial class OffsetPointData : OffsetData {
        
        private string pointField;
        
        public string Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    public partial class OffsetDistanceData : OffsetData {
        
        private DistanceData distanceField;
        
        private bool leftField;
        
        public OffsetDistanceData() {
            this.distanceField = new DistanceData();
            this.leftField = false;
        }
        
        public DistanceData Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParallelData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BearingData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AngleData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeflectionData))]
    public partial class DirectionData : ObservationData {
        
        private OffsetData offsetField;
        
        public OffsetData Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
    }
    
    public partial class ParallelData : DirectionData {
        
        private string fromField;
        
        private string startField;
        
        private string endField;
        
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        public string Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        public string End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
    }
    
    public partial class BearingData : DirectionData {
        
        private string valueField;
        
        private string fromField;
        
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeflectionData))]
    public partial class AngleData : DirectionData {
        
        private string valueField;
        
        private string fromField;
        
        private string backsightField;
        
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        public string Backsight {
            get {
                return this.backsightField;
            }
            set {
                this.backsightField = value;
            }
        }
    }
    
    public partial class DeflectionData : AngleData {
    }
    
    public partial class CalculatedFeatureData : FeatureData {
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RowTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MiscTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeyTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SharedPointData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PointData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SegmentData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SectionData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiSegmentData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArcData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CalculatedFeatureData))]
    public abstract partial class FeatureData {
        
        private string idField;
        
        private int entityField;
        
        private uint keyField;
        
        private bool keyFieldSpecified;
        
        private string foreignKeyField;
        
        public FeatureData() {
            this.entityField = 0;
        }
        
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        public uint Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        public bool KeySpecified {
            get {
                return this.keyFieldSpecified;
            }
            set {
                this.keyFieldSpecified = value;
            }
        }
        
        public string ForeignKey {
            get {
                return this.foreignKeyField;
            }
            set {
                this.foreignKeyField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RowTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MiscTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeyTextData))]
    public abstract partial class TextData : FeatureData {
        
        private long xField;
        
        private long yField;
        
        private double heightField;
        
        private double widthField;
        
        private string rotationField;
        
        private int fontField;
        
        private bool fontFieldSpecified;
        
        private bool topologicalField;
        
        private long polygonXField;
        
        private bool polygonXFieldSpecified;
        
        private long polygonYField;
        
        private bool polygonYFieldSpecified;
        
        public TextData() {
            this.topologicalField = true;
        }
        
        public long X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        public long Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        public double Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        public double Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        public string Rotation {
            get {
                return this.rotationField;
            }
            set {
                this.rotationField = value;
            }
        }
        
        public int Font {
            get {
                return this.fontField;
            }
            set {
                this.fontField = value;
            }
        }
        
        public bool FontSpecified {
            get {
                return this.fontFieldSpecified;
            }
            set {
                this.fontFieldSpecified = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Topological {
            get {
                return this.topologicalField;
            }
            set {
                this.topologicalField = value;
            }
        }
        
        public long PolygonX {
            get {
                return this.polygonXField;
            }
            set {
                this.polygonXField = value;
            }
        }
        
        public bool PolygonXSpecified {
            get {
                return this.polygonXFieldSpecified;
            }
            set {
                this.polygonXFieldSpecified = value;
            }
        }
        
        public long PolygonY {
            get {
                return this.polygonYField;
            }
            set {
                this.polygonYField = value;
            }
        }
        
        public bool PolygonYSpecified {
            get {
                return this.polygonYFieldSpecified;
            }
            set {
                this.polygonYFieldSpecified = value;
            }
        }
    }
    
    public partial class RowTextData : TextData {
        
        private uint tableField;
        
        private uint templateField;
        
        public uint Table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
            }
        }
        
        public uint Template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
            }
        }
    }
    
    public partial class MiscTextData : TextData {
        
        private string textField;
        
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    public partial class KeyTextData : TextData {
    }
    
    public partial class SharedPointData : FeatureData {
        
        private string firstPointField;
        
        public string FirstPoint {
            get {
                return this.firstPointField;
            }
            set {
                this.firstPointField = value;
            }
        }
    }
    
    public partial class PointData : FeatureData {
        
        private long xField;
        
        private long yField;
        
        private long zField;
        
        private bool zFieldSpecified;
        
        public long X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        public long Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        public long Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
        
        public bool ZSpecified {
            get {
                return this.zFieldSpecified;
            }
            set {
                this.zFieldSpecified = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SegmentData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SectionData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiSegmentData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArcData))]
    public abstract partial class LineData : FeatureData {
        
        private string fromField;
        
        private string toField;
        
        private bool topologicalField;
        
        public LineData() {
            this.topologicalField = true;
        }
        
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Topological {
            get {
                return this.topologicalField;
            }
            set {
                this.topologicalField = value;
            }
        }
    }
    
    public partial class SegmentData : LineData {
    }
    
    public partial class SectionData : LineData {
        
        private string baseField;
        
        public string Base {
            get {
                return this.baseField;
            }
            set {
                this.baseField = value;
            }
        }
    }
    
    public partial class MultiSegmentData : LineData {
        
        private List<PointGeometryData> pointField;
        
        public MultiSegmentData() {
            this.pointField = new List<PointGeometryData>();
        }
        
        public List<PointGeometryData> Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    public partial class PointGeometryData {
        
        private long xField;
        
        private long yField;
        
        private long zField;
        
        private bool zFieldSpecified;
        
        public long X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        public long Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        public long Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
        
        public bool ZSpecified {
            get {
                return this.zFieldSpecified;
            }
            set {
                this.zFieldSpecified = value;
            }
        }
    }
    
    public partial class ArcData : LineData {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private bool clockwiseField;
        
        public ArcData() {
            this.clockwiseField = false;
        }
        
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Clockwise {
            get {
                return this.clockwiseField;
            }
            set {
                this.clockwiseField = value;
            }
        }
    }
    
    public enum ItemChoiceType {
        
        /// <remarks/>
        Center,
        
        /// <remarks/>
        FirstArc,
    }
    
    public partial class StraightLegData : LegData {
        
        private string startAngleField;
        
        private bool deflectionField;
        
        public StraightLegData() {
            this.deflectionField = false;
        }
        
        public string StartAngle {
            get {
                return this.startAngleField;
            }
            set {
                this.startAngleField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Deflection {
            get {
                return this.deflectionField;
            }
            set {
                this.deflectionField = value;
            }
        }
    }
    
    public partial class CircularLegData : LegData {
        
        private DistanceData radiusField;
        
        private CalculatedFeatureData centerField;
        
        private string angle1Field;
        
        private string angle2Field;
        
        private bool culDeSacField;
        
        private bool clockwiseField;
        
        public CircularLegData() {
            this.centerField = new CalculatedFeatureData();
            this.radiusField = new DistanceData();
            this.culDeSacField = false;
        }
        
        public DistanceData Radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
        
        public CalculatedFeatureData Center {
            get {
                return this.centerField;
            }
            set {
                this.centerField = value;
            }
        }
        
        public string Angle1 {
            get {
                return this.angle1Field;
            }
            set {
                this.angle1Field = value;
            }
        }
        
        public string Angle2 {
            get {
                return this.angle2Field;
            }
            set {
                this.angle2Field = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool CulDeSac {
            get {
                return this.culDeSacField;
            }
            set {
                this.culDeSacField = value;
            }
        }
        
        public bool Clockwise {
            get {
                return this.clockwiseField;
            }
            set {
                this.clockwiseField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineExtensionUpdateData))]
    public abstract partial class UpdateData : OperationData {
        
        private string revisedEditField;
        
        public string RevisedEdit {
            get {
                return this.revisedEditField;
            }
            set {
                this.revisedEditField = value;
            }
        }
    }
    
    public partial class LineExtensionUpdateData : UpdateData {
        
        private DistanceData distanceField;
        
        private bool extendFromEndField;
        
        public LineExtensionUpdateData() {
            this.distanceField = new DistanceData();
            this.extendFromEndField = false;
        }
        
        public DistanceData Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ExtendFromEnd {
            get {
                return this.extendFromEndField;
            }
            set {
                this.extendFromEndField = value;
            }
        }
    }
    
    public partial class TrimLineData : OperationData {
        
        private List<string> lineField;
        
        private List<string> pointField;
        
        public TrimLineData() {
            this.pointField = new List<string>();
            this.lineField = new List<string>();
        }
        
        public List<string> Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        public List<string> Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    public partial class TextRotationData : OperationData {
        
        private string valueField;
        
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    public partial class SimpleLineSubdivisionData : OperationData {
        
        private DistanceData distanceField;
        
        private CalculatedFeatureData newPointField;
        
        private string lineField;
        
        private string newLine1Field;
        
        private string newLine2Field;
        
        public SimpleLineSubdivisionData() {
            this.newPointField = new CalculatedFeatureData();
            this.distanceField = new DistanceData();
        }
        
        public DistanceData Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        public CalculatedFeatureData NewPoint {
            get {
                return this.newPointField;
            }
            set {
                this.newPointField = value;
            }
        }
        
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        public string NewLine1 {
            get {
                return this.newLine1Field;
            }
            set {
                this.newLine1Field = value;
            }
        }
        
        public string NewLine2 {
            get {
                return this.newLine2Field;
            }
            set {
                this.newLine2Field = value;
            }
        }
    }
    
    public partial class SetTopologyData : OperationData {
        
        private string lineField;
        
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
    }
    
    public partial class RadialData : OperationData {
        
        private DirectionData directionField;
        
        private ObservationData lengthField;
        
        private CalculatedFeatureData toField;
        
        private CalculatedFeatureData lineField;
        
        public RadialData() {
            this.lineField = new CalculatedFeatureData();
            this.toField = new CalculatedFeatureData();
            this.directionField = new DirectionData();
        }
        
        public DirectionData Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        public ObservationData Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        public CalculatedFeatureData To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        public CalculatedFeatureData Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
    }
    
    public partial class PropertyChangeData : OperationData {
        
        private PropertyItemData itemField;
        
        private string valueField;
        
        public PropertyItemData Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    public enum PropertyItemData {
        
        /// <remarks/>
        DefaultPointType,
        
        /// <remarks/>
        DefaultLineType,
        
        /// <remarks/>
        DefaultTextType,
        
        /// <remarks/>
        DefaultPolygonType,
    }
    
    public partial class PolygonSubdivisionData : OperationData {
        
        private List<SegmentData> lineField;
        
        private string deactivatedLabelField;
        
        public PolygonSubdivisionData() {
            this.lineField = new List<SegmentData>();
        }
        
        public List<SegmentData> Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        public string DeactivatedLabel {
            get {
                return this.deactivatedLabelField;
            }
            set {
                this.deactivatedLabelField = value;
            }
        }
    }
    
    public partial class PathData : OperationData {
        
        private List<LegData> legField;
        
        private string fromField;
        
        private string toField;
        
        private string entryStringField;
        
        private int lineTypeField;
        
        private int pointTypeField;
        
        public PathData() {
            this.legField = new List<LegData>();
        }
        
        public List<LegData> Leg {
            get {
                return this.legField;
            }
            set {
                this.legField = value;
            }
        }
        
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        public string EntryString {
            get {
                return this.entryStringField;
            }
            set {
                this.entryStringField = value;
            }
        }
        
        public int LineType {
            get {
                return this.lineTypeField;
            }
            set {
                this.lineTypeField = value;
            }
        }
        
        public int PointType {
            get {
                return this.pointTypeField;
            }
            set {
                this.pointTypeField = value;
            }
        }
    }
    
    public partial class ParallelLineData : OperationData {
        
        private ObservationData offsetField;
        
        private CalculatedFeatureData fromField;
        
        private CalculatedFeatureData toField;
        
        private LineData newLineField;
        
        private string refLineField;
        
        private string term1Field;
        
        private string term2Field;
        
        private bool reverseArcField;
        
        public ParallelLineData() {
            this.toField = new CalculatedFeatureData();
            this.fromField = new CalculatedFeatureData();
            this.reverseArcField = false;
        }
        
        public ObservationData Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        public CalculatedFeatureData From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        public CalculatedFeatureData To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        public LineData NewLine {
            get {
                return this.newLineField;
            }
            set {
                this.newLineField = value;
            }
        }
        
        public string RefLine {
            get {
                return this.refLineField;
            }
            set {
                this.refLineField = value;
            }
        }
        
        public string Term1 {
            get {
                return this.term1Field;
            }
            set {
                this.term1Field = value;
            }
        }
        
        public string Term2 {
            get {
                return this.term2Field;
            }
            set {
                this.term2Field = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReverseArc {
            get {
                return this.reverseArcField;
            }
            set {
                this.reverseArcField = value;
            }
        }
    }
    
    public partial class NewSegmentData : OperationData {
        
        private SegmentData lineField;
        
        public NewSegmentData() {
            this.lineField = new SegmentData();
        }
        
        public SegmentData Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
    }
    
    public partial class NewRowTextData : OperationData {
        
        private RowTextData textField;
        
        public NewRowTextData() {
            this.textField = new RowTextData();
        }
        
        public RowTextData Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    public partial class NewPointData : OperationData {
        
        private PointData pointField;
        
        public NewPointData() {
            this.pointField = new PointData();
        }
        
        public PointData Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    public partial class NewMiscTextData : OperationData {
        
        private MiscTextData textField;
        
        public NewMiscTextData() {
            this.textField = new MiscTextData();
        }
        
        public MiscTextData Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    public partial class NewKeyTextData : OperationData {
        
        private KeyTextData textField;
        
        public NewKeyTextData() {
            this.textField = new KeyTextData();
        }
        
        public KeyTextData Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    public partial class NewCircleData : OperationData {
        
        private ObservationData radiusField;
        
        private string centerField;
        
        private string closingPointField;
        
        private string arcField;
        
        public ObservationData Radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
        
        public string Center {
            get {
                return this.centerField;
            }
            set {
                this.centerField = value;
            }
        }
        
        public string ClosingPoint {
            get {
                return this.closingPointField;
            }
            set {
                this.closingPointField = value;
            }
        }
        
        public string Arc {
            get {
                return this.arcField;
            }
            set {
                this.arcField = value;
            }
        }
    }
    
    public partial class NewArcData : OperationData {
        
        private ArcData lineField;
        
        public NewArcData() {
            this.lineField = new ArcData();
        }
        
        public ArcData Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
    }
    
    public partial class MoveTextData : OperationData {
        
        private string textField;
        
        private long oldXField;
        
        private long oldYField;
        
        private long oldPolygonXField;
        
        private bool oldPolygonXFieldSpecified;
        
        private long oldPolygonYField;
        
        private bool oldPolygonYFieldSpecified;
        
        private long newXField;
        
        private long newYField;
        
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        public long OldX {
            get {
                return this.oldXField;
            }
            set {
                this.oldXField = value;
            }
        }
        
        public long OldY {
            get {
                return this.oldYField;
            }
            set {
                this.oldYField = value;
            }
        }
        
        public long OldPolygonX {
            get {
                return this.oldPolygonXField;
            }
            set {
                this.oldPolygonXField = value;
            }
        }
        
        public bool OldPolygonXSpecified {
            get {
                return this.oldPolygonXFieldSpecified;
            }
            set {
                this.oldPolygonXFieldSpecified = value;
            }
        }
        
        public long OldPolygonY {
            get {
                return this.oldPolygonYField;
            }
            set {
                this.oldPolygonYField = value;
            }
        }
        
        public bool OldPolygonYSpecified {
            get {
                return this.oldPolygonYFieldSpecified;
            }
            set {
                this.oldPolygonYFieldSpecified = value;
            }
        }
        
        public long NewX {
            get {
                return this.newXField;
            }
            set {
                this.newXField = value;
            }
        }
        
        public long NewY {
            get {
                return this.newYField;
            }
            set {
                this.newYField = value;
            }
        }
    }
    
    public partial class MovePolygonPositionData : OperationData {
        
        private string labelField;
        
        private long newXField;
        
        private long newYField;
        
        private long oldXField;
        
        private bool oldXFieldSpecified;
        
        private long oldYField;
        
        private bool oldYFieldSpecified;
        
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        public long NewX {
            get {
                return this.newXField;
            }
            set {
                this.newXField = value;
            }
        }
        
        public long NewY {
            get {
                return this.newYField;
            }
            set {
                this.newYField = value;
            }
        }
        
        public long OldX {
            get {
                return this.oldXField;
            }
            set {
                this.oldXField = value;
            }
        }
        
        public bool OldXSpecified {
            get {
                return this.oldXFieldSpecified;
            }
            set {
                this.oldXFieldSpecified = value;
            }
        }
        
        public long OldY {
            get {
                return this.oldYField;
            }
            set {
                this.oldYField = value;
            }
        }
        
        public bool OldYSpecified {
            get {
                return this.oldYFieldSpecified;
            }
            set {
                this.oldYFieldSpecified = value;
            }
        }
    }
    
    public partial class LineSubdivisionData : OperationData {
        
        private List<SpanData> spanField;
        
        private string lineField;
        
        public LineSubdivisionData() {
            this.spanField = new List<SpanData>();
        }
        
        public List<SpanData> Span {
            get {
                return this.spanField;
            }
            set {
                this.spanField = value;
            }
        }
        
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
    }
    
    public partial class LineExtensionData : OperationData {
        
        private DistanceData distanceField;
        
        private CalculatedFeatureData newPointField;
        
        private CalculatedFeatureData newLineField;
        
        private string lineField;
        
        private bool extendFromEndField;
        
        public LineExtensionData() {
            this.newLineField = new CalculatedFeatureData();
            this.newPointField = new CalculatedFeatureData();
            this.distanceField = new DistanceData();
            this.extendFromEndField = false;
        }
        
        public DistanceData Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        public CalculatedFeatureData NewPoint {
            get {
                return this.newPointField;
            }
            set {
                this.newPointField = value;
            }
        }
        
        public CalculatedFeatureData NewLine {
            get {
                return this.newLineField;
            }
            set {
                this.newLineField = value;
            }
        }
        
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ExtendFromEnd {
            get {
                return this.extendFromEndField;
            }
            set {
                this.extendFromEndField = value;
            }
        }
    }
    
    public partial class IntersectTwoLinesData : OperationData {
        
        private CalculatedFeatureData toField;
        
        private string line1Field;
        
        private string line2Field;
        
        private string closeToField;
        
        private string splitBefore1Field;
        
        private string splitAfter1Field;
        
        private string splitBefore2Field;
        
        private string splitAfter2Field;
        
        public IntersectTwoLinesData() {
            this.toField = new CalculatedFeatureData();
        }
        
        public CalculatedFeatureData To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        public string Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
            }
        }
        
        public string Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
            }
        }
        
        public string CloseTo {
            get {
                return this.closeToField;
            }
            set {
                this.closeToField = value;
            }
        }
        
        public string SplitBefore1 {
            get {
                return this.splitBefore1Field;
            }
            set {
                this.splitBefore1Field = value;
            }
        }
        
        public string SplitAfter1 {
            get {
                return this.splitAfter1Field;
            }
            set {
                this.splitAfter1Field = value;
            }
        }
        
        public string SplitBefore2 {
            get {
                return this.splitBefore2Field;
            }
            set {
                this.splitBefore2Field = value;
            }
        }
        
        public string SplitAfter2 {
            get {
                return this.splitAfter2Field;
            }
            set {
                this.splitAfter2Field = value;
            }
        }
    }
    
    public partial class IntersectTwoDistancesData : OperationData {
        
        private ObservationData distance1Field;
        
        private ObservationData distance2Field;
        
        private CalculatedFeatureData toField;
        
        private CalculatedFeatureData line1Field;
        
        private CalculatedFeatureData line2Field;
        
        private string from1Field;
        
        private string from2Field;
        
        private bool defaultField;
        
        public IntersectTwoDistancesData() {
            this.line2Field = new CalculatedFeatureData();
            this.line1Field = new CalculatedFeatureData();
            this.toField = new CalculatedFeatureData();
            this.defaultField = false;
        }
        
        public ObservationData Distance1 {
            get {
                return this.distance1Field;
            }
            set {
                this.distance1Field = value;
            }
        }
        
        public ObservationData Distance2 {
            get {
                return this.distance2Field;
            }
            set {
                this.distance2Field = value;
            }
        }
        
        public CalculatedFeatureData To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        public CalculatedFeatureData Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
            }
        }
        
        public CalculatedFeatureData Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
            }
        }
        
        public string From1 {
            get {
                return this.from1Field;
            }
            set {
                this.from1Field = value;
            }
        }
        
        public string From2 {
            get {
                return this.from2Field;
            }
            set {
                this.from2Field = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
    }
    
    public partial class IntersectTwoDirectionsData : OperationData {
        
        private DirectionData direction1Field;
        
        private DirectionData direction2Field;
        
        private CalculatedFeatureData toField;
        
        private CalculatedFeatureData line1Field;
        
        private CalculatedFeatureData line2Field;
        
        public IntersectTwoDirectionsData() {
            this.line2Field = new CalculatedFeatureData();
            this.line1Field = new CalculatedFeatureData();
            this.toField = new CalculatedFeatureData();
            this.direction2Field = new DirectionData();
            this.direction1Field = new DirectionData();
        }
        
        public DirectionData Direction1 {
            get {
                return this.direction1Field;
            }
            set {
                this.direction1Field = value;
            }
        }
        
        public DirectionData Direction2 {
            get {
                return this.direction2Field;
            }
            set {
                this.direction2Field = value;
            }
        }
        
        public CalculatedFeatureData To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        public CalculatedFeatureData Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
            }
        }
        
        public CalculatedFeatureData Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
            }
        }
    }
    
    public partial class IntersectDirectionAndLineData : OperationData {
        
        private DirectionData directionField;
        
        private CalculatedFeatureData toField;
        
        private CalculatedFeatureData dirLineField;
        
        private string closeToField;
        
        private string lineField;
        
        private string splitBeforeField;
        
        private string splitAfterField;
        
        public IntersectDirectionAndLineData() {
            this.dirLineField = new CalculatedFeatureData();
            this.toField = new CalculatedFeatureData();
            this.directionField = new DirectionData();
        }
        
        public DirectionData Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        public CalculatedFeatureData To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        public CalculatedFeatureData DirLine {
            get {
                return this.dirLineField;
            }
            set {
                this.dirLineField = value;
            }
        }
        
        public string CloseTo {
            get {
                return this.closeToField;
            }
            set {
                this.closeToField = value;
            }
        }
        
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        public string SplitBefore {
            get {
                return this.splitBeforeField;
            }
            set {
                this.splitBeforeField = value;
            }
        }
        
        public string SplitAfter {
            get {
                return this.splitAfterField;
            }
            set {
                this.splitAfterField = value;
            }
        }
    }
    
    public partial class IntersectDirectionAndDistanceData : OperationData {
        
        private DirectionData directionField;
        
        private ObservationData distanceField;
        
        private CalculatedFeatureData toField;
        
        private CalculatedFeatureData dirLineField;
        
        private CalculatedFeatureData distLineField;
        
        private string fromField;
        
        private bool defaultField;
        
        public IntersectDirectionAndDistanceData() {
            this.distLineField = new CalculatedFeatureData();
            this.dirLineField = new CalculatedFeatureData();
            this.toField = new CalculatedFeatureData();
            this.directionField = new DirectionData();
            this.defaultField = false;
        }
        
        public DirectionData Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        public ObservationData Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        public CalculatedFeatureData To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        public CalculatedFeatureData DirLine {
            get {
                return this.dirLineField;
            }
            set {
                this.dirLineField = value;
            }
        }
        
        public CalculatedFeatureData DistLine {
            get {
                return this.distLineField;
            }
            set {
                this.distLineField = value;
            }
        }
        
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
    }
    
    public partial class ImportData : OperationData {
        
        private List<FeatureData> featureField;
        
        public ImportData() {
            this.featureField = new List<FeatureData>();
        }
        
        public List<FeatureData> Feature {
            get {
                return this.featureField;
            }
            set {
                this.featureField = value;
            }
        }
    }
    
    public partial class GetControlData : OperationData {
        
        private List<PointData> pointField;
        
        public GetControlData() {
            this.pointField = new List<PointData>();
        }
        
        public List<PointData> Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    public partial class DeletionData : OperationData {
        
        private List<string> deleteField;
        
        public DeletionData() {
            this.deleteField = new List<string>();
        }
        
        public List<string> Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
            }
        }
    }
    
    public partial class AttachPointData : OperationData {
        
        private CalculatedFeatureData pointField;
        
        private string lineField;
        
        private uint positionRatioField;
        
        public AttachPointData() {
            this.pointField = new CalculatedFeatureData();
        }
        
        public CalculatedFeatureData Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
        
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        public uint PositionRatio {
            get {
                return this.positionRatioField;
            }
            set {
                this.positionRatioField = value;
            }
        }
    }
}
