//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace Backsight.Editor.Xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    [System.Xml.Serialization.XmlRootAttribute("Edit", Namespace="Backsight", IsNullable=false)]
    public partial class EditType {
        
        private OperationType[] operationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Operation")]
        public OperationType[] Operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonSubdivisionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewTextType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewSegmentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewPointType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewCircleType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewArcType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MoveTextType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MovePolygonPositionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineSubdivisionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineExtensionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntersectTwoLinesType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntersectTwoDistancesType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntersectTwoDirectionsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntersectDirectionAndLineType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntersectDirectionAndDistanceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImportType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetControlType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeletionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttachPointType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public abstract partial class OperationType {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class SpanType {
        
        private DistanceType lengthField;
        
        private object itemField;
        
        private CalculatedFeatureType endPointField;
        
        /// <remarks/>
        public DistanceType Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Line", typeof(CalculatedFeatureType))]
        [System.Xml.Serialization.XmlElementAttribute("LineId", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        public CalculatedFeatureType EndPoint {
            get {
                return this.endPointField;
            }
            set {
                this.endPointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class DistanceType : ObservationType {
        
        private double valueField;
        
        private int unitField;
        
        private bool fixedField;
        
        public DistanceType() {
            this.unitField = 0;
            this.fixedField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Fixed {
            get {
                return this.fixedField;
            }
            set {
                this.fixedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DistanceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OffsetType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OffsetPointType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OffsetDistanceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DirectionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParallelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BearingType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AngleType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeflectionType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public abstract partial class ObservationType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OffsetPointType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OffsetDistanceType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public abstract partial class OffsetType : ObservationType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class OffsetPointType : OffsetType {
        
        private string pointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class OffsetDistanceType : OffsetType {
        
        private DistanceType distanceField;
        
        private bool leftField;
        
        public OffsetDistanceType() {
            this.leftField = false;
        }
        
        /// <remarks/>
        public DistanceType Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParallelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BearingType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AngleType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeflectionType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class DirectionType : ObservationType {
        
        private OffsetType offsetField;
        
        /// <remarks/>
        public OffsetType Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class ParallelType : DirectionType {
        
        private string fromField;
        
        private string startField;
        
        private string endField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class BearingType : DirectionType {
        
        private string valueField;
        
        private string fromField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeflectionType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class AngleType : DirectionType {
        
        private string valueField;
        
        private string fromField;
        
        private string backsightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Backsight {
            get {
                return this.backsightField;
            }
            set {
                this.backsightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class DeflectionType : AngleType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class CalculatedFeatureType : FeatureType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RowTextType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MiscTextType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeyTextType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SharedPointType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PointType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SegmentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SectionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiSegmentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArcType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CalculatedFeatureType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public abstract partial class FeatureType {
        
        private string idField;
        
        private int typeField;
        
        private uint keyField;
        
        private bool keyFieldSpecified;
        
        private string foreignKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KeySpecified {
            get {
                return this.keyFieldSpecified;
            }
            set {
                this.keyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ForeignKey {
            get {
                return this.foreignKeyField;
            }
            set {
                this.foreignKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RowTextType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MiscTextType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeyTextType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public abstract partial class TextType : FeatureType {
        
        private long xField;
        
        private long yField;
        
        private double heightField;
        
        private double widthField;
        
        private string rotationField;
        
        private int fontField;
        
        private bool fontFieldSpecified;
        
        private bool topologicalField;
        
        private long polygonXField;
        
        private bool polygonXFieldSpecified;
        
        private long polygonYField;
        
        private bool polygonYFieldSpecified;
        
        public TextType() {
            this.topologicalField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Rotation {
            get {
                return this.rotationField;
            }
            set {
                this.rotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Font {
            get {
                return this.fontField;
            }
            set {
                this.fontField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FontSpecified {
            get {
                return this.fontFieldSpecified;
            }
            set {
                this.fontFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Topological {
            get {
                return this.topologicalField;
            }
            set {
                this.topologicalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long PolygonX {
            get {
                return this.polygonXField;
            }
            set {
                this.polygonXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PolygonXSpecified {
            get {
                return this.polygonXFieldSpecified;
            }
            set {
                this.polygonXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long PolygonY {
            get {
                return this.polygonYField;
            }
            set {
                this.polygonYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PolygonYSpecified {
            get {
                return this.polygonYFieldSpecified;
            }
            set {
                this.polygonYFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class RowTextType : TextType {
        
        private string rowKeyField;
        
        private uint tableField;
        
        private uint templateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RowKey {
            get {
                return this.rowKeyField;
            }
            set {
                this.rowKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class MiscTextType : TextType {
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class KeyTextType : TextType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class SharedPointType : FeatureType {
        
        private string firstPointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FirstPoint {
            get {
                return this.firstPointField;
            }
            set {
                this.firstPointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class PointType : FeatureType {
        
        private long xField;
        
        private long yField;
        
        private long zField;
        
        private bool zFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZSpecified {
            get {
                return this.zFieldSpecified;
            }
            set {
                this.zFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SegmentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SectionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiSegmentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArcType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public abstract partial class LineType : FeatureType {
        
        private string fromField;
        
        private string toField;
        
        private bool topologicalField;
        
        public LineType() {
            this.topologicalField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Topological {
            get {
                return this.topologicalField;
            }
            set {
                this.topologicalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class SegmentType : LineType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class SectionType : LineType {
        
        private string baseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Base {
            get {
                return this.baseField;
            }
            set {
                this.baseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class MultiSegmentType : LineType {
        
        private PointGeometryType[] pointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Point")]
        public PointGeometryType[] Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class PointGeometryType {
        
        private long xField;
        
        private long yField;
        
        private long zField;
        
        private bool zFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZSpecified {
            get {
                return this.zFieldSpecified;
            }
            set {
                this.zFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class ArcType : LineType {
        
        private object itemField;
        
        private bool clockwiseField;
        
        public ArcType() {
            this.clockwiseField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Circle", typeof(CircleType))]
        [System.Xml.Serialization.XmlElementAttribute("FirstArc", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Clockwise {
            get {
                return this.clockwiseField;
            }
            set {
                this.clockwiseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class CircleType {
        
        private string centerField;
        
        private double radiusField;
        
        private bool radiusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Center {
            get {
                return this.centerField;
            }
            set {
                this.centerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RadiusSpecified {
            get {
                return this.radiusFieldSpecified;
            }
            set {
                this.radiusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class PolygonSubdivisionType : OperationType {
        
        private SegmentType[] lineField;
        
        private string deactivatedLabelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Line")]
        public SegmentType[] Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DeactivatedLabel {
            get {
                return this.deactivatedLabelField;
            }
            set {
                this.deactivatedLabelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class NewTextType : OperationType {
        
        private TextType textField;
        
        /// <remarks/>
        public TextType Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class NewSegmentType : OperationType {
        
        private SegmentType lineField;
        
        /// <remarks/>
        public SegmentType Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class NewPointType : OperationType {
        
        private PointType pointField;
        
        /// <remarks/>
        public PointType Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class NewCircleType : OperationType {
        
        private ObservationType radiusField;
        
        private string centerField;
        
        private string closingPointField;
        
        private string arcField;
        
        /// <remarks/>
        public ObservationType Radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Center {
            get {
                return this.centerField;
            }
            set {
                this.centerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClosingPoint {
            get {
                return this.closingPointField;
            }
            set {
                this.closingPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Arc {
            get {
                return this.arcField;
            }
            set {
                this.arcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class NewArcType : OperationType {
        
        private ArcType lineField;
        
        /// <remarks/>
        public ArcType Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class MoveTextType : OperationType {
        
        private string textField;
        
        private long oldXField;
        
        private long oldYField;
        
        private long oldPolygonXField;
        
        private bool oldPolygonXFieldSpecified;
        
        private long oldPolygonYField;
        
        private bool oldPolygonYFieldSpecified;
        
        private long newXField;
        
        private long newYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long OldX {
            get {
                return this.oldXField;
            }
            set {
                this.oldXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long OldY {
            get {
                return this.oldYField;
            }
            set {
                this.oldYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long OldPolygonX {
            get {
                return this.oldPolygonXField;
            }
            set {
                this.oldPolygonXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OldPolygonXSpecified {
            get {
                return this.oldPolygonXFieldSpecified;
            }
            set {
                this.oldPolygonXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long OldPolygonY {
            get {
                return this.oldPolygonYField;
            }
            set {
                this.oldPolygonYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OldPolygonYSpecified {
            get {
                return this.oldPolygonYFieldSpecified;
            }
            set {
                this.oldPolygonYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long NewX {
            get {
                return this.newXField;
            }
            set {
                this.newXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long NewY {
            get {
                return this.newYField;
            }
            set {
                this.newYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class MovePolygonPositionType : OperationType {
        
        private string labelField;
        
        private long newXField;
        
        private long newYField;
        
        private long oldXField;
        
        private bool oldXFieldSpecified;
        
        private long oldYField;
        
        private bool oldYFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long NewX {
            get {
                return this.newXField;
            }
            set {
                this.newXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long NewY {
            get {
                return this.newYField;
            }
            set {
                this.newYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long OldX {
            get {
                return this.oldXField;
            }
            set {
                this.oldXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OldXSpecified {
            get {
                return this.oldXFieldSpecified;
            }
            set {
                this.oldXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long OldY {
            get {
                return this.oldYField;
            }
            set {
                this.oldYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OldYSpecified {
            get {
                return this.oldYFieldSpecified;
            }
            set {
                this.oldYFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class LineSubdivisionType : OperationType {
        
        private SpanType[] spanField;
        
        private string lineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Span")]
        public SpanType[] Span {
            get {
                return this.spanField;
            }
            set {
                this.spanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class LineExtensionType : OperationType {
        
        private DistanceType distanceField;
        
        private CalculatedFeatureType newPointField;
        
        private CalculatedFeatureType newLineField;
        
        private string lineField;
        
        private bool extendFromEndField;
        
        public LineExtensionType() {
            this.extendFromEndField = false;
        }
        
        /// <remarks/>
        public DistanceType Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        public CalculatedFeatureType NewPoint {
            get {
                return this.newPointField;
            }
            set {
                this.newPointField = value;
            }
        }
        
        /// <remarks/>
        public CalculatedFeatureType NewLine {
            get {
                return this.newLineField;
            }
            set {
                this.newLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ExtendFromEnd {
            get {
                return this.extendFromEndField;
            }
            set {
                this.extendFromEndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class IntersectTwoLinesType : OperationType {
        
        private CalculatedFeatureType toField;
        
        private string line1Field;
        
        private string line2Field;
        
        private string closeToField;
        
        private string splitBefore1Field;
        
        private string splitAfter1Field;
        
        private string splitBefore2Field;
        
        private string splitAfter2Field;
        
        /// <remarks/>
        public CalculatedFeatureType To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CloseTo {
            get {
                return this.closeToField;
            }
            set {
                this.closeToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SplitBefore1 {
            get {
                return this.splitBefore1Field;
            }
            set {
                this.splitBefore1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SplitAfter1 {
            get {
                return this.splitAfter1Field;
            }
            set {
                this.splitAfter1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SplitBefore2 {
            get {
                return this.splitBefore2Field;
            }
            set {
                this.splitBefore2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SplitAfter2 {
            get {
                return this.splitAfter2Field;
            }
            set {
                this.splitAfter2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class IntersectTwoDistancesType : OperationType {
        
        private ObservationType distance1Field;
        
        private ObservationType distance2Field;
        
        private CalculatedFeatureType toField;
        
        private CalculatedFeatureType line1Field;
        
        private CalculatedFeatureType line2Field;
        
        private string from1Field;
        
        private string from2Field;
        
        private bool defaultField;
        
        public IntersectTwoDistancesType() {
            this.defaultField = false;
        }
        
        /// <remarks/>
        public ObservationType Distance1 {
            get {
                return this.distance1Field;
            }
            set {
                this.distance1Field = value;
            }
        }
        
        /// <remarks/>
        public ObservationType Distance2 {
            get {
                return this.distance2Field;
            }
            set {
                this.distance2Field = value;
            }
        }
        
        /// <remarks/>
        public CalculatedFeatureType To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public CalculatedFeatureType Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
            }
        }
        
        /// <remarks/>
        public CalculatedFeatureType Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string From1 {
            get {
                return this.from1Field;
            }
            set {
                this.from1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string From2 {
            get {
                return this.from2Field;
            }
            set {
                this.from2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class IntersectTwoDirectionsType : OperationType {
        
        private DirectionType direction1Field;
        
        private DirectionType direction2Field;
        
        private CalculatedFeatureType toField;
        
        private CalculatedFeatureType line1Field;
        
        private CalculatedFeatureType line2Field;
        
        /// <remarks/>
        public DirectionType Direction1 {
            get {
                return this.direction1Field;
            }
            set {
                this.direction1Field = value;
            }
        }
        
        /// <remarks/>
        public DirectionType Direction2 {
            get {
                return this.direction2Field;
            }
            set {
                this.direction2Field = value;
            }
        }
        
        /// <remarks/>
        public CalculatedFeatureType To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public CalculatedFeatureType Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
            }
        }
        
        /// <remarks/>
        public CalculatedFeatureType Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class IntersectDirectionAndLineType : OperationType {
        
        private DirectionType directionField;
        
        private CalculatedFeatureType toField;
        
        private CalculatedFeatureType dirLineField;
        
        private string closeToField;
        
        private string lineField;
        
        private string splitBeforeField;
        
        private string splitAfterField;
        
        /// <remarks/>
        public DirectionType Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        public CalculatedFeatureType To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public CalculatedFeatureType DirLine {
            get {
                return this.dirLineField;
            }
            set {
                this.dirLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CloseTo {
            get {
                return this.closeToField;
            }
            set {
                this.closeToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SplitBefore {
            get {
                return this.splitBeforeField;
            }
            set {
                this.splitBeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SplitAfter {
            get {
                return this.splitAfterField;
            }
            set {
                this.splitAfterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class IntersectDirectionAndDistanceType : OperationType {
        
        private DirectionType directionField;
        
        private ObservationType distanceField;
        
        private CalculatedFeatureType toField;
        
        private CalculatedFeatureType dirLineField;
        
        private CalculatedFeatureType distLineField;
        
        private string fromField;
        
        private bool defaultField;
        
        public IntersectDirectionAndDistanceType() {
            this.defaultField = false;
        }
        
        /// <remarks/>
        public DirectionType Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        public ObservationType Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        public CalculatedFeatureType To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public CalculatedFeatureType DirLine {
            get {
                return this.dirLineField;
            }
            set {
                this.dirLineField = value;
            }
        }
        
        /// <remarks/>
        public CalculatedFeatureType DistLine {
            get {
                return this.distLineField;
            }
            set {
                this.distLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class ImportType : OperationType {
        
        private FeatureType[] featureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Feature")]
        public FeatureType[] Feature {
            get {
                return this.featureField;
            }
            set {
                this.featureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class GetControlType : OperationType {
        
        private PointType[] pointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Point")]
        public PointType[] Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class DeletionType : OperationType {
        
        private string[] deleteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Delete")]
        public string[] Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class AttachPointType : OperationType {
        
        private CalculatedFeatureType pointField;
        
        private string lineField;
        
        private uint positionRatioField;
        
        /// <remarks/>
        public CalculatedFeatureType Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint PositionRatio {
            get {
                return this.positionRatioField;
            }
            set {
                this.positionRatioField = value;
            }
        }
    }
}
