//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Backsight.Editor.Xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    [System.Xml.Serialization.XmlRootAttribute("Edit", Namespace="Backsight", IsNullable=false)]
    public partial class EditData {
        
        private OperationData[] operationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Operation")]
        public OperationData[] Operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineExtensionUpdateData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TrimLineData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextRotationData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SimpleLineSubdivisionData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetTopologyData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RadialData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PolygonSubdivisionData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PathData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParallelLineData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewSegmentData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewRowTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewPointData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewMiscTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewKeyTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewCircleData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewArcData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MoveTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MovePolygonPositionData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineSubdivisionData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineExtensionData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntersectTwoLinesData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntersectTwoDistancesData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntersectTwoDirectionsData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntersectDirectionAndLineData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntersectDirectionAndDistanceData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImportData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetControlData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeletionData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttachPointData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public abstract partial class OperationData {
        
        private string idField;
        
        private string previousIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PreviousId {
            get {
                return this.previousIdField;
            }
            set {
                this.previousIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class FactoryData {
        
        private FeatureStubData[] dataField;
        
        private int defaultLineEntityField;
        
        private bool defaultLineEntityFieldSpecified;
        
        private int defaultPointEntityField;
        
        private bool defaultPointEntityFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Data")]
        public FeatureStubData[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DefaultLineEntity {
            get {
                return this.defaultLineEntityField;
            }
            set {
                this.defaultLineEntityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DefaultLineEntitySpecified {
            get {
                return this.defaultLineEntityFieldSpecified;
            }
            set {
                this.defaultLineEntityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DefaultPointEntity {
            get {
                return this.defaultPointEntityField;
            }
            set {
                this.defaultPointEntityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DefaultPointEntitySpecified {
            get {
                return this.defaultPointEntityFieldSpecified;
            }
            set {
                this.defaultPointEntityFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FeatureData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RowTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MiscTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeyTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PointData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SegmentData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SectionData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiSegmentData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArcData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class FeatureStubData {
        
        private string idField;
        
        private int entityField;
        
        private uint keyField;
        
        private bool keyFieldSpecified;
        
        private string foreignKeyField;
        
        public FeatureStubData() {
            this.entityField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KeySpecified {
            get {
                return this.keyFieldSpecified;
            }
            set {
                this.keyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ForeignKey {
            get {
                return this.foreignKeyField;
            }
            set {
                this.foreignKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RowTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MiscTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeyTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PointData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SegmentData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SectionData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiSegmentData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArcData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public abstract partial class FeatureData : FeatureStubData {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RowTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MiscTextData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeyTextData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public abstract partial class TextData : FeatureData {
        
        private long xField;
        
        private long yField;
        
        private double heightField;
        
        private double widthField;
        
        private string rotationField;
        
        private int fontField;
        
        private bool fontFieldSpecified;
        
        private bool topologicalField;
        
        private long polygonXField;
        
        private bool polygonXFieldSpecified;
        
        private long polygonYField;
        
        private bool polygonYFieldSpecified;
        
        public TextData() {
            this.topologicalField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Rotation {
            get {
                return this.rotationField;
            }
            set {
                this.rotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Font {
            get {
                return this.fontField;
            }
            set {
                this.fontField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FontSpecified {
            get {
                return this.fontFieldSpecified;
            }
            set {
                this.fontFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Topological {
            get {
                return this.topologicalField;
            }
            set {
                this.topologicalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long PolygonX {
            get {
                return this.polygonXField;
            }
            set {
                this.polygonXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PolygonXSpecified {
            get {
                return this.polygonXFieldSpecified;
            }
            set {
                this.polygonXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long PolygonY {
            get {
                return this.polygonYField;
            }
            set {
                this.polygonYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PolygonYSpecified {
            get {
                return this.polygonYFieldSpecified;
            }
            set {
                this.polygonYFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class RowTextData : TextData {
        
        private uint tableField;
        
        private uint templateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Table {
            get {
                return this.tableField;
            }
            set {
                this.tableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint Template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class MiscTextData : TextData {
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class KeyTextData : TextData {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class PointData : FeatureData {
        
        private long xField;
        
        private long yField;
        
        private long zField;
        
        private bool zFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZSpecified {
            get {
                return this.zFieldSpecified;
            }
            set {
                this.zFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SegmentData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SectionData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultiSegmentData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArcData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public abstract partial class LineData : FeatureData {
        
        private string fromField;
        
        private string toField;
        
        private bool topologicalField;
        
        public LineData() {
            this.topologicalField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Topological {
            get {
                return this.topologicalField;
            }
            set {
                this.topologicalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class SegmentData : LineData {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class SectionData : LineData {
        
        private string baseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Base {
            get {
                return this.baseField;
            }
            set {
                this.baseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class MultiSegmentData : LineData {
        
        private PointGeometryData[] pointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Point")]
        public PointGeometryData[] Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class PointGeometryData {
        
        private long xField;
        
        private long yField;
        
        private long zField;
        
        private bool zFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZSpecified {
            get {
                return this.zFieldSpecified;
            }
            set {
                this.zFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class ArcData : LineData {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private bool clockwiseField;
        
        public ArcData() {
            this.clockwiseField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Center", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("FirstArc", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Clockwise {
            get {
                return this.clockwiseField;
            }
            set {
                this.clockwiseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        Center,
        
        /// <remarks/>
        FirstArc,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DistanceData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OffsetData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OffsetPointData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OffsetDistanceData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DirectionData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParallelData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BearingData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AngleData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeflectionData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public abstract partial class ObservationData {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class DistanceData : ObservationData {
        
        private double valueField;
        
        private int unitField;
        
        private bool fixedField;
        
        public DistanceData() {
            this.unitField = 0;
            this.fixedField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Fixed {
            get {
                return this.fixedField;
            }
            set {
                this.fixedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OffsetPointData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OffsetDistanceData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public abstract partial class OffsetData : ObservationData {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class OffsetPointData : OffsetData {
        
        private string pointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class OffsetDistanceData : OffsetData {
        
        private DistanceData distanceField;
        
        private bool leftField;
        
        public OffsetDistanceData() {
            this.leftField = false;
        }
        
        /// <remarks/>
        public DistanceData Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParallelData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BearingData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AngleData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeflectionData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public abstract partial class DirectionData : ObservationData {
        
        private OffsetData offsetField;
        
        /// <remarks/>
        public OffsetData Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class ParallelData : DirectionData {
        
        private string fromField;
        
        private string startField;
        
        private string endField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class BearingData : DirectionData {
        
        private string valueField;
        
        private string fromField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeflectionData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class AngleData : DirectionData {
        
        private string valueField;
        
        private string fromField;
        
        private string backsightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Backsight {
            get {
                return this.backsightField;
            }
            set {
                this.backsightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class DeflectionData : AngleData {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LineExtensionUpdateData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public abstract partial class UpdateData : OperationData {
        
        private string revisedEditField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RevisedEdit {
            get {
                return this.revisedEditField;
            }
            set {
                this.revisedEditField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class LineExtensionUpdateData : UpdateData {
        
        private DistanceData distanceField;
        
        private bool extendFromEndField;
        
        public LineExtensionUpdateData() {
            this.extendFromEndField = false;
        }
        
        /// <remarks/>
        public DistanceData Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ExtendFromEnd {
            get {
                return this.extendFromEndField;
            }
            set {
                this.extendFromEndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class TrimLineData : OperationData {
        
        private string[] lineField;
        
        private string[] pointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Line")]
        public string[] Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Point")]
        public string[] Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class TextRotationData : OperationData {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class SimpleLineSubdivisionData : OperationData {
        
        private DistanceData distanceField;
        
        private FeatureStubData newPointField;
        
        private string lineField;
        
        private string newLine1Field;
        
        private string newLine2Field;
        
        /// <remarks/>
        public DistanceData Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        public FeatureStubData NewPoint {
            get {
                return this.newPointField;
            }
            set {
                this.newPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewLine1 {
            get {
                return this.newLine1Field;
            }
            set {
                this.newLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewLine2 {
            get {
                return this.newLine2Field;
            }
            set {
                this.newLine2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class SetTopologyData : OperationData {
        
        private string lineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class RadialData : OperationData {
        
        private DirectionData directionField;
        
        private ObservationData lengthField;
        
        private FeatureStubData toField;
        
        private FeatureStubData lineField;
        
        /// <remarks/>
        public DirectionData Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        public ObservationData Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public FeatureStubData To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public FeatureStubData Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class PolygonSubdivisionData : OperationData {
        
        private SegmentData[] lineField;
        
        private string deactivatedLabelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Line")]
        public SegmentData[] Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DeactivatedLabel {
            get {
                return this.deactivatedLabelField;
            }
            set {
                this.deactivatedLabelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class PathData : OperationData {
        
        private FactoryData resultField;
        
        private string fromField;
        
        private string toField;
        
        private string entryStringField;
        
        private int defaultEntryUnitField;
        
        /// <remarks/>
        public FactoryData Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EntryString {
            get {
                return this.entryStringField;
            }
            set {
                this.entryStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DefaultEntryUnit {
            get {
                return this.defaultEntryUnitField;
            }
            set {
                this.defaultEntryUnitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class ParallelLineData : OperationData {
        
        private ObservationData offsetField;
        
        private FeatureStubData fromField;
        
        private FeatureStubData toField;
        
        private FeatureStubData newLineField;
        
        private string refLineField;
        
        private string term1Field;
        
        private string term2Field;
        
        private bool reverseArcField;
        
        public ParallelLineData() {
            this.reverseArcField = false;
        }
        
        /// <remarks/>
        public ObservationData Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        public FeatureStubData From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public FeatureStubData To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public FeatureStubData NewLine {
            get {
                return this.newLineField;
            }
            set {
                this.newLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RefLine {
            get {
                return this.refLineField;
            }
            set {
                this.refLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Term1 {
            get {
                return this.term1Field;
            }
            set {
                this.term1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Term2 {
            get {
                return this.term2Field;
            }
            set {
                this.term2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReverseArc {
            get {
                return this.reverseArcField;
            }
            set {
                this.reverseArcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class NewSegmentData : OperationData {
        
        private SegmentData lineField;
        
        /// <remarks/>
        public SegmentData Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class NewRowTextData : OperationData {
        
        private RowTextData textField;
        
        /// <remarks/>
        public RowTextData Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class NewPointData : OperationData {
        
        private PointData pointField;
        
        /// <remarks/>
        public PointData Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class NewMiscTextData : OperationData {
        
        private MiscTextData textField;
        
        /// <remarks/>
        public MiscTextData Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class NewKeyTextData : OperationData {
        
        private KeyTextData textField;
        
        /// <remarks/>
        public KeyTextData Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class NewCircleData : OperationData {
        
        private ObservationData radiusField;
        
        private string centerField;
        
        private string closingPointField;
        
        private string arcField;
        
        /// <remarks/>
        public ObservationData Radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Center {
            get {
                return this.centerField;
            }
            set {
                this.centerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClosingPoint {
            get {
                return this.closingPointField;
            }
            set {
                this.closingPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Arc {
            get {
                return this.arcField;
            }
            set {
                this.arcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class NewArcData : OperationData {
        
        private ArcData lineField;
        
        /// <remarks/>
        public ArcData Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class MoveTextData : OperationData {
        
        private string textField;
        
        private long oldXField;
        
        private long oldYField;
        
        private long oldPolygonXField;
        
        private bool oldPolygonXFieldSpecified;
        
        private long oldPolygonYField;
        
        private bool oldPolygonYFieldSpecified;
        
        private long newXField;
        
        private long newYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long OldX {
            get {
                return this.oldXField;
            }
            set {
                this.oldXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long OldY {
            get {
                return this.oldYField;
            }
            set {
                this.oldYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long OldPolygonX {
            get {
                return this.oldPolygonXField;
            }
            set {
                this.oldPolygonXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OldPolygonXSpecified {
            get {
                return this.oldPolygonXFieldSpecified;
            }
            set {
                this.oldPolygonXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long OldPolygonY {
            get {
                return this.oldPolygonYField;
            }
            set {
                this.oldPolygonYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OldPolygonYSpecified {
            get {
                return this.oldPolygonYFieldSpecified;
            }
            set {
                this.oldPolygonYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long NewX {
            get {
                return this.newXField;
            }
            set {
                this.newXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long NewY {
            get {
                return this.newYField;
            }
            set {
                this.newYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class MovePolygonPositionData : OperationData {
        
        private string labelField;
        
        private long newXField;
        
        private long newYField;
        
        private long oldXField;
        
        private bool oldXFieldSpecified;
        
        private long oldYField;
        
        private bool oldYFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long NewX {
            get {
                return this.newXField;
            }
            set {
                this.newXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long NewY {
            get {
                return this.newYField;
            }
            set {
                this.newYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long OldX {
            get {
                return this.oldXField;
            }
            set {
                this.oldXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OldXSpecified {
            get {
                return this.oldXFieldSpecified;
            }
            set {
                this.oldXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long OldY {
            get {
                return this.oldYField;
            }
            set {
                this.oldYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OldYSpecified {
            get {
                return this.oldYFieldSpecified;
            }
            set {
                this.oldYFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class LineSubdivisionData : OperationData {
        
        private FactoryData resultField;
        
        private string lineField;
        
        private string entryStringField;
        
        private int defaultEntryUnitField;
        
        private bool entryFromEndField;
        
        /// <remarks/>
        public FactoryData Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string EntryString {
            get {
                return this.entryStringField;
            }
            set {
                this.entryStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DefaultEntryUnit {
            get {
                return this.defaultEntryUnitField;
            }
            set {
                this.defaultEntryUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool EntryFromEnd {
            get {
                return this.entryFromEndField;
            }
            set {
                this.entryFromEndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class LineExtensionData : OperationData {
        
        private DistanceData distanceField;
        
        private FeatureStubData newPointField;
        
        private FeatureStubData newLineField;
        
        private string lineField;
        
        private bool extendFromEndField;
        
        public LineExtensionData() {
            this.extendFromEndField = false;
        }
        
        /// <remarks/>
        public DistanceData Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        public FeatureStubData NewPoint {
            get {
                return this.newPointField;
            }
            set {
                this.newPointField = value;
            }
        }
        
        /// <remarks/>
        public FeatureStubData NewLine {
            get {
                return this.newLineField;
            }
            set {
                this.newLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ExtendFromEnd {
            get {
                return this.extendFromEndField;
            }
            set {
                this.extendFromEndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class IntersectTwoLinesData : OperationData {
        
        private FeatureStubData toField;
        
        private string line1Field;
        
        private string line2Field;
        
        private string closeToField;
        
        private string splitBefore1Field;
        
        private string splitAfter1Field;
        
        private string splitBefore2Field;
        
        private string splitAfter2Field;
        
        /// <remarks/>
        public FeatureStubData To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CloseTo {
            get {
                return this.closeToField;
            }
            set {
                this.closeToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SplitBefore1 {
            get {
                return this.splitBefore1Field;
            }
            set {
                this.splitBefore1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SplitAfter1 {
            get {
                return this.splitAfter1Field;
            }
            set {
                this.splitAfter1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SplitBefore2 {
            get {
                return this.splitBefore2Field;
            }
            set {
                this.splitBefore2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SplitAfter2 {
            get {
                return this.splitAfter2Field;
            }
            set {
                this.splitAfter2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class IntersectTwoDistancesData : OperationData {
        
        private ObservationData distance1Field;
        
        private ObservationData distance2Field;
        
        private FeatureStubData toField;
        
        private FeatureStubData line1Field;
        
        private FeatureStubData line2Field;
        
        private string from1Field;
        
        private string from2Field;
        
        private bool defaultField;
        
        public IntersectTwoDistancesData() {
            this.defaultField = false;
        }
        
        /// <remarks/>
        public ObservationData Distance1 {
            get {
                return this.distance1Field;
            }
            set {
                this.distance1Field = value;
            }
        }
        
        /// <remarks/>
        public ObservationData Distance2 {
            get {
                return this.distance2Field;
            }
            set {
                this.distance2Field = value;
            }
        }
        
        /// <remarks/>
        public FeatureStubData To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public FeatureStubData Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
            }
        }
        
        /// <remarks/>
        public FeatureStubData Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string From1 {
            get {
                return this.from1Field;
            }
            set {
                this.from1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string From2 {
            get {
                return this.from2Field;
            }
            set {
                this.from2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class IntersectTwoDirectionsData : OperationData {
        
        private DirectionData direction1Field;
        
        private DirectionData direction2Field;
        
        private FeatureStubData toField;
        
        private FeatureStubData line1Field;
        
        private FeatureStubData line2Field;
        
        /// <remarks/>
        public DirectionData Direction1 {
            get {
                return this.direction1Field;
            }
            set {
                this.direction1Field = value;
            }
        }
        
        /// <remarks/>
        public DirectionData Direction2 {
            get {
                return this.direction2Field;
            }
            set {
                this.direction2Field = value;
            }
        }
        
        /// <remarks/>
        public FeatureStubData To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public FeatureStubData Line1 {
            get {
                return this.line1Field;
            }
            set {
                this.line1Field = value;
            }
        }
        
        /// <remarks/>
        public FeatureStubData Line2 {
            get {
                return this.line2Field;
            }
            set {
                this.line2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class IntersectDirectionAndLineData : OperationData {
        
        private DirectionData directionField;
        
        private FeatureStubData toField;
        
        private FeatureStubData dirLineField;
        
        private string closeToField;
        
        private string lineField;
        
        private string splitBeforeField;
        
        private string splitAfterField;
        
        /// <remarks/>
        public DirectionData Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        public FeatureStubData To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public FeatureStubData DirLine {
            get {
                return this.dirLineField;
            }
            set {
                this.dirLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CloseTo {
            get {
                return this.closeToField;
            }
            set {
                this.closeToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SplitBefore {
            get {
                return this.splitBeforeField;
            }
            set {
                this.splitBeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SplitAfter {
            get {
                return this.splitAfterField;
            }
            set {
                this.splitAfterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class IntersectDirectionAndDistanceData : OperationData {
        
        private DirectionData directionField;
        
        private ObservationData distanceField;
        
        private FeatureStubData toField;
        
        private FeatureStubData dirLineField;
        
        private FeatureStubData distLineField;
        
        private string fromField;
        
        private bool defaultField;
        
        public IntersectDirectionAndDistanceData() {
            this.defaultField = false;
        }
        
        /// <remarks/>
        public DirectionData Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        public ObservationData Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        public FeatureStubData To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public FeatureStubData DirLine {
            get {
                return this.dirLineField;
            }
            set {
                this.dirLineField = value;
            }
        }
        
        /// <remarks/>
        public FeatureStubData DistLine {
            get {
                return this.distLineField;
            }
            set {
                this.distLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class ImportData : OperationData {
        
        private FeatureData[] featureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Feature")]
        public FeatureData[] Feature {
            get {
                return this.featureField;
            }
            set {
                this.featureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class GetControlData : OperationData {
        
        private PointData[] pointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Point")]
        public PointData[] Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class DeletionData : OperationData {
        
        private string[] deleteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Delete")]
        public string[] Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Backsight")]
    public partial class AttachPointData : OperationData {
        
        private FeatureStubData pointField;
        
        private string lineField;
        
        private uint positionRatioField;
        
        /// <remarks/>
        public FeatureStubData Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint PositionRatio {
            get {
                return this.positionRatioField;
            }
            set {
                this.positionRatioField = value;
            }
        }
    }
}
