namespace Backsight.Database;

/// <summary>
/// Metadata for a column in a miscellaneous attribute table.
/// </summary>
/// <param name="Name">The name of the column.</param>
/// <param name="DataType">The type of data held in the column.</param>
/// <param name="Nullable">Is the column nullable?</param>
/// <param name="PrimaryKey">Does the column form part of the primary key?</param>
public record ColumnInfo(string Name, Type DataType, bool Nullable, bool PrimaryKey)
{
    public bool IsAutoGeneratedPrimaryKey => PrimaryKey && DataType == typeof(int);
}